bazel-bin/syntaxnet/parser_trainer \
  --task_context=syntaxnet/context.pbtxt \
  --compute_lexicon \
  --graph_builder=greedy \
  --training_corpus=training-corpus \
  --tuning_corpus=tuning-corpus \
  --output_path=models \
  --batch_size=32 \
  --decay_steps=8000 \
  --hidden_layer_sizes=128 \
  --learning_rate=0.09 \
  --momentum=0.9 \
  --seed=2 \
  --params=128-0.08-8000-0.9-0
